export { default as logo } from './logotext-removebg-preview (2).png';
export { default as logo2 } from './Stylized__N__Logo_Design-removebg-preview__3_-removebg-preview.png';

export { default as ArrowRight } from './arrow-right.svg';
export { default as cog } from './360_F_1209914771_7NfFOOt2DObbebTDEi3u8VFsJrqmZKdJ-removebg-preview (2).png';
export { default as cylinder } from './cylinder.png';
export { default as noodle } from './noodle.png';
export { default as avatar1 } from "./profile_logo_LinkedIn_38938430.jpg";
export { default as avatar2 } from "./prostori-za-vencanja-q4525y0zmssa7pu08duhjmtr5tqnn26cxbr1z92mty.webp";
export { default as avatar3 } from "./554478369_18534583150060446_3101763340558053102_n.jpg";
export { default as avatar4 } from "./download.jpg";
export { default as avatar5 } from "./download.jpg";
export { default as avatar6 } from "./download.jpg";
export { default as avatar7 } from "./download.jpg";
export { default as avatar8 } from "./download.jpg";
export { default as avatar9 } from "./554478369_18534583150060446_3101763340558053102_n.jpg";
export { default as acme } from "./logo3.jpg";
export { default as apex } from "./logo1.jpg";
export { default as celestial } from "./logo4.jpg";
export { default as echo } from "./logo2.jpg";
export { default as pulse } from "./logo3.jpg";
export { default as quantum } from "./logo1.jpg";
export { default as instagram } from './social-insta.svg';
export { default as linkedin } from './social-linkedin.svg';
export { default as pin } from './social-pin.svg';
export { default as x } from './social-x.svg';
export { default as youtube } from './social-youtube.svg';
export { default as spring } from './OIP-removebg-preview.png';
export { default as star } from './OIP-removebg-preview.png';
export { default as productImage } from './product-image.png';
export { default as pyramid } from './pyramid.png';
export { default as tube } from './stock-vector-vivid-rainbow-floating-soap-bubble-illustration-vector-collection-delicate-and-bright-design-2657365805-removebg-preview.png';
export { default as check } from './check.svg';
export { default as checkwhite } from './checkwhite.svg';
export { default as arrowRightWhite } from './arrow-right-white.svg';
export { default as icons} from './pngtree-free-delivery-truck-icon-png-image_8951758-removebg-preview (1).png';
